import {useEffect,useRef,useState} from 'preact/hooks';
import sheetUrl from './assets/tiny-dungeon.png';
import {act,chooseUpgrade,enter,fresh,rooms,update,type Game,type Life,type Upgrade} from './game';
const codes:Record<string,string>={ArrowUp:'up',KeyW:'up',ArrowDown:'down',KeyS:'down',ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',Space:'dash',KeyF:'toss',KeyJ:'brace',KeyE:'interact',Escape:'pause',KeyM:'mute'};
const names:Record<Upgrade,[string,string]>={'quickstep-charm':['Quickstep Charm','Two deterministic dash charges.'],'ember-shard':['Ember Shard','Toss pierces and burns.'],'iron-wrap':['Iron Wrap','100 max HP; damage adds more Instability.'],'voltaic-core':['Voltaic Core','Surge begins at 40; passive decay stops.'],'steady-hand':['Steady Hand','Brace builds half Instability.'],'charm-bearers-grip':["Charm-Bearer's Grip",'Four Toss charges; rune recharge doubles.']};
const storageKey='goblin-courier:v2';
type Saved={mute:boolean;reducedMotion:boolean;bestScore:number;deliveries:number};
const readSave=():Saved=>{try{return {...{mute:false,reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,bestScore:0,deliveries:0},...JSON.parse(localStorage.getItem(storageKey)||'{}')}}catch{return {mute:false,reducedMotion:false,bestScore:0,deliveries:0}}};
function setLife(g:Game,l:Life,render:()=>void){g.life=l;document.documentElement.dataset.widgetState=l==='title'?'ready':'populated';if(__GAME_TEST_BUILD__)document.documentElement.dataset.gameState=l;render()}
export function App(){const initial=useRef(readSave());const game=useRef(fresh());const canvas=useRef<HTMLCanvasElement>(null);const shell=useRef<HTMLElement>(null);const keys=useRef(new Set<string>());const pointers=useRef(new Map<number,{kind:'move'|'brace';x:number;y:number}>());const touches=useRef(new Map<number,{kind:'move'|'brace';x:number;y:number}>());const [tick,setTick]=useState(0);const [muted,setMuted]=useState(initial.current.mute);const [reduced,setReduced]=useState(initial.current.reducedMotion);const [stats,setStats]=useState({bestScore:initial.current.bestScore,deliveries:initial.current.deliveries});const rerender=()=>setTick(v=>v+1);void tick;
 const syncHeld=()=>{const all=[...pointers.current.values(),...touches.current.values()];['left','right','up','down','brace'].forEach(k=>keys.current.delete(k));for(const p of all){if(p.kind==='brace'){keys.current.add('brace');continue}if(Math.abs(p.x)>.18)keys.current.add(p.x>0?'right':'left');if(Math.abs(p.y)>.18)keys.current.add(p.y>0?'down':'up')}};
 const tone=(hz=220)=>{if(muted)return;try{const A=window.AudioContext||(window as any).webkitAudioContext,c=new A(),o=c.createOscillator(),gain=c.createGain();o.frequency.value=hz;gain.gain.setValueAtTime(.04,c.currentTime);gain.gain.exponentialRampToValueAtTime(.001,c.currentTime+.08);o.connect(gain).connect(c.destination);o.start();o.stop(c.currentTime+.09)}catch{}};
 const doAct=(a:string)=>{const g=game.current;if(a==='pause'){if(g.life==='choosing')setLife(g,'playing',rerender);else if(g.life==='playing')setLife(g,'paused',rerender);else if(g.life==='paused')setLife(g,'playing',rerender);return}if(a==='mute'){setMuted(v=>!v);return}act(g,a);tone(a==='toss'?440:180);rerender()};
 const start=()=>{game.current=fresh();game.current.life='playing';document.documentElement.dataset.widgetState='populated';if(__GAME_TEST_BUILD__)document.documentElement.dataset.gameState='playing';rerender();tone(330)};
 useEffect(()=>{try{localStorage.setItem(storageKey,JSON.stringify({mute:muted,reducedMotion:reduced,...stats}))}catch{}},[muted,reduced,stats]);
 useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)'),change=(e:MediaQueryListEvent)=>setReduced(e.matches);mq.addEventListener?.('change',change);return()=>mq.removeEventListener?.('change',change)},[]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{const k=codes[e.code];if(!k)return;e.preventDefault();if(['pause','mute','dash','toss','interact'].includes(k)){if(!e.repeat)doAct(k)}else keys.current.add(k)};const up=(e:KeyboardEvent)=>{const k=codes[e.code];if(k)keys.current.delete(k)};const vis=()=>{if(document.hidden&&game.current.life==='playing')setLife(game.current,'paused',rerender)};addEventListener('keydown',down);addEventListener('keyup',up);document.addEventListener('visibilitychange',vis);return()=>{removeEventListener('keydown',down);removeEventListener('keyup',up);document.removeEventListener('visibilitychange',vis)}},[muted]);
 useEffect(()=>{let raf=0,last=game.current.life,recorded=false;const loop=()=>{update(game.current,keys.current);if(game.current.life!==last){last=game.current.life;document.documentElement.dataset.widgetState=last==='title'?'ready':'populated';if(__GAME_TEST_BUILD__)document.documentElement.dataset.gameState=last;if(last==='won'&&!recorded){recorded=true;setStats(s=>({deliveries:s.deliveries+1,bestScore:Math.max(s.bestScore,game.current.score)}))}rerender()}draw();if(game.current.frames%3===0)rerender();raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf)},[]);
 useEffect(()=>{const el=shell.current;if(!el)return;const post=()=>{const r=el.getBoundingClientRect();parent.postMessage({type:'widget-resize',widget:'goblin-courier',width:Math.round(r.width),height:Math.round(r.height)},'*')};const ro=new ResizeObserver(post);ro.observe(el);post();return()=>ro.disconnect()},[]);
 useEffect(()=>{document.documentElement.dataset.widgetState='ready';if(__GAME_TEST_BUILD__)document.documentElement.dataset.gameState='title';requestAnimationFrame(()=>{if(!document.getElementById('widget-ready')){const m=document.createElement('div');m.id='widget-ready';m.className='ready-marker';m.setAttribute('aria-hidden','true');document.body.append(m)}if(__GAME_TEST_BUILD__&&!document.getElementById('game-ready')){const m=document.createElement('div');m.id='game-ready';m.className='ready-marker';m.setAttribute('aria-hidden','true');document.body.append(m)}});if(__GAME_TEST_BUILD__)(window as any).__game={getState:()=>JSON.parse(JSON.stringify(game.current)),getScore:()=>game.current.score,getRoom:()=>rooms[game.current.room].id,getUpgrades:()=>[...game.current.upgrades],getStats:()=>readSave(),start,setupRoom:(n:number)=>{game.current=fresh();game.current.life='playing';enter(game.current,n);document.documentElement.dataset.gameState='playing';document.documentElement.dataset.widgetState='populated';rerender()},setEnemyHp:(n:number)=>{game.current.enemies.forEach(e=>e.hp=n)},setBossHp:(n:number)=>{const e=game.current.enemies.find(e=>e.kind==='warden');if(e)e.hp=n},setPosition:(x:number,y:number)=>{game.current.x=x;game.current.y=y},setInstability:(n:number)=>game.current.instability=n,grantUpgrade:(id:Upgrade)=>{game.current.offers=[id];game.current.life='choosing';chooseUpgrade(game.current,id);rerender()}};return()=>{if(__GAME_TEST_BUILD__)delete (window as any).__game}},[]);
 useEffect(()=>{if(__GAME_TEST_BUILD__)(window as any).__game.enterRoom=(n:number)=>{enter(game.current,n);rerender()}},[]);
 useEffect(()=>{const joy=document.getElementById('joystick-zone');if(!joy)return;const onJoy=(e:TouchEvent)=>{(e as any)._gcHandled=true;e.preventDefault();if(e.type==='touchend'||e.type==='touchcancel'){for(const t of Array.from(e.changedTouches))touches.current.delete(t.identifier)}else for(const t of Array.from(e.changedTouches)){const r=joy.getBoundingClientRect();touches.current.set(t.identifier,{kind:'move',x:Math.max(-1,Math.min(1,(t.clientX-(r.left+r.width/2))/(r.width*.35))),y:Math.max(-1,Math.min(1,(t.clientY-(r.top+r.height/2))/(r.height*.35)))})}syncHeld()};const cleanups:(()=>void)[]=[];for(const type of ['touchstart','touchmove','touchend','touchcancel'] as const){joy.addEventListener(type,onJoy,{passive:false});cleanups.push(()=>joy.removeEventListener(type,onJoy))}for(const kind of ['dash','toss','brace','interact'] as const){const el=document.getElementById(`${kind}-button`);if(!el)continue;const onStart=(e:TouchEvent)=>{(e as any)._gcHandled=true;e.preventDefault();for(const t of Array.from(e.changedTouches)){if(kind==='brace')touches.current.set(t.identifier,{kind:'brace',x:0,y:0});else doAct(kind)}syncHeld()};const onEnd=(e:TouchEvent)=>{(e as any)._gcHandled=true;e.preventDefault();for(const t of Array.from(e.changedTouches))touches.current.delete(t.identifier);syncHeld()};el.addEventListener('touchstart',onStart,{passive:false});el.addEventListener('touchend',onEnd,{passive:false});el.addEventListener('touchcancel',onEnd,{passive:false});cleanups.push(()=>{el.removeEventListener('touchstart',onStart);el.removeEventListener('touchend',onEnd);el.removeEventListener('touchcancel',onEnd)})}return()=>cleanups.forEach(f=>f())},[]);
 const draw=()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d')!,g=game.current,dpr=Math.min(devicePixelRatio||1,2);if(c.width!==960*dpr||c.height!==600*dpr){c.width=960*dpr;c.height=600*dpr}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=false;ctx.fillStyle=['#171326','#1d1828','#20162c','#182239','#2a1722','#1c2530','#261b31','#201a30','#17252b','#241422','#1b2430'][g.room];ctx.fillRect(0,0,960,600);const img=(draw as any).img||((draw as any).img=new Image());if(!img.src)img.src=sheetUrl;const tile=(i:number,x:number,y:number,s=48)=>{if(img.complete)ctx.drawImage(img,(i%12)*16,Math.floor(i/12)*16,16,16,x,y,s,s)};for(let y=60;y<550;y+=48)for(let x=40;x<930;x+=48)tile((x/48+y/48+g.room)%3?0:12,x,y);for(let x=40;x<930;x+=48){tile(40,x,44);tile(40,x,540)}for(let y=92;y<540;y+=48){tile(40,40,y);tile(40,904,y)}if(g.room===1)[250,470,700].forEach((x,i)=>tile(7,x,130+i%2*300));if(g.room===2||g.room===5){ctx.fillStyle='#fff1ca';ctx.font='20px Kenney';ctx.fillText(g.room===2?'SAFE / CHEST':'CONTINUE',210,140);ctx.fillText(g.room===2?'FAST / COMBAT':'STOREROOM',210,475)}if(g.room===3)tile(g.gate?44:32,690,270,64);if(g.room===6||g.room===9){ctx.strokeStyle=g.bossPhase===3?'#7fffd4':'#b56cff';ctx.lineWidth=10;ctx.beginPath();ctx.arc(480,300,72,0,Math.PI*2);ctx.stroke();tile(89,760,280,56)}if(g.room===7){for(let x=340;x<650;x+=55)tile(g.hazard>45?41:25,x,210+(x%110),52)}if(g.room===10)tile(89,780,270,72);for(const e of g.enemies)if(e.hp>0){if(e.telegraph){ctx.strokeStyle=e.kind==='warden'?'#ffcc55':'#ff6677';ctx.lineWidth=5;ctx.beginPath();ctx.arc(e.x,e.y,35+e.telegraph,0,Math.PI*2);ctx.stroke()}tile(e.kind==='grunt'?96:e.kind==='weaver'?84:e.kind==='sentinel'?100:98,e.x-24,e.y-24,e.kind==='warden'?72:48);ctx.fillStyle='#ef4c5b';ctx.fillRect(e.x-25,e.y-38,50*Math.max(0,e.hp/e.maxHp),5)}for(const p of g.projectiles){ctx.fillStyle=p.owner==='enemy'?'#ff5678':'#ffd34e';ctx.beginPath();ctx.arc(p.x,p.y,p.owner==='enemy'?9:7,0,Math.PI*2);ctx.fill()}if(!reduced&&g.instability>=60){ctx.strokeStyle=g.instability>=90?'#ef4c5b':'#f0a93b';ctx.lineWidth=8+Math.sin(g.frames/5)*3;ctx.strokeRect(5,5,950,590)}tile(112,g.x-24,g.y-24,48);tile(66,g.x+10,g.y+8,24);ctx.fillStyle='#fff1ca';ctx.font='18px Kenney';ctx.fillText(`${rooms[g.room].name} · ${g.message}`,55,35)};
 const vector=(el:HTMLElement,x:number,y:number)=>{const r=el.getBoundingClientRect();return {x:Math.max(-1,Math.min(1,(x-(r.left+r.width/2))/(r.width*.35))),y:Math.max(-1,Math.min(1,(y-(r.top+r.height/2))/(r.height*.35)))}};
 const pointerMove=(e:PointerEvent)=>{const p=pointers.current.get(e.pointerId);if(!p||p.kind!=='move')return;Object.assign(p,vector(e.currentTarget as HTMLElement,e.clientX,e.clientY));syncHeld()};
 const touchMove=(e:TouchEvent)=>{if((e as any)._gcHandled)return;e.preventDefault();for(const t of Array.from(e.changedTouches)){const p=touches.current.get(t.identifier);if(p?.kind==='move')Object.assign(p,vector(e.currentTarget as HTMLElement,t.clientX,t.clientY))}syncHeld()};
 const touchEnd=(e:TouchEvent)=>{if((e as any)._gcHandled)return;e.preventDefault();for(const t of Array.from(e.changedTouches))touches.current.delete(t.identifier);syncHeld()};
 const actionPointer=(kind:'brace'|'dash'|'toss'|'interact',e:PointerEvent)=>{if(kind==='brace'){pointers.current.set(e.pointerId,{kind:'brace',x:0,y:0});(e.currentTarget as HTMLElement).setPointerCapture?.(e.pointerId);syncHeld()}else doAct(kind)};
 const actionTouch=(kind:'brace'|'dash'|'toss'|'interact',e:TouchEvent)=>{if((e as any)._gcHandled)return;e.preventDefault();for(const t of Array.from(e.changedTouches)){if(kind==='brace')touches.current.set(t.identifier,{kind:'brace',x:0,y:0});else doAct(kind)}syncHeld()};
 const test=(id:string)=>(__GAME_TEST_BUILD__?{'data-testid':id}:{});const g=game.current,band=g.instability>=90?'critical':g.instability>=(g.upgrades.includes('voltaic-core')?40:60)?'surge':'';
 return <main ref={shell} class={`shell ${reduced?'reduced':''}`}><header class="top"><h1>Goblin Courier</h1><button {...test('pause-button')} aria-label="Pause or resume" onClick={()=>doAct('pause')}>{g.life==='paused'?'Resume':'Pause'}</button><button {...test('mute-button')} aria-label="Mute audio" onClick={()=>doAct('mute')}>{muted?'Sound off':'Sound on'}</button><button {...test('motion-button')} aria-label="Toggle reduced motion" aria-pressed={reduced} onClick={()=>setReduced(v=>!v)}>{reduced?'Still':'Motion'}</button></header><section class="stage"><canvas ref={canvas} id="game-canvas" aria-label={`Goblin Courier game: ${rooms[g.room].name}`}/>{g.life!=='title'&&<div class="hud"><span class="chip">HP <b id="hp-value" {...test('hp-value')}>{Math.max(0,Math.ceil(g.hp))}/{g.maxHp}</b></span><span class="chip" id="charges">Dash {g.dash}/{g.dashMax} · Toss {g.toss}/{g.tossMax}</span><span class="chip meter" id="instability-meter" {...test('instability-meter')}>Instability {Math.floor(g.instability)}% · {band||'steady'}<span class="meter-track"><span class={`meter-fill ${band}`} style={{width:`${g.instability}%`}}/></span></span>{g.room===9&&<span class="chip" id="boss-status">WARDEN PHASE {g.bossPhase||1} · {g.bossPattern||'watch'}</span>}</div>}
 {g.life==='title'&&<div class="overlay"><div class="card"><h2>THE LAST TITHE</h2><p>Eleven authored rooms. Clear enemies before using exits; choose the safe chest route or fast barracks route.</p><p><b>Move</b> WASD/arrows · <b>Dash</b> Space · <b>Toss</b> F · <b>Brace</b> J · <b>Use</b> E</p><p>Deliveries {stats.deliveries} · Best {stats.bestScore}</p><button id="start-button" {...test('start-button')} onClick={start}>Take the charm</button></div></div>}{g.life==='paused'&&<div class="overlay" id="pause-overlay" {...test('pause-overlay')}><div class="card"><h2>PAUSED</h2><button onClick={()=>doAct('pause')}>Continue</button></div></div>}{g.life==='choosing'&&<div class="overlay"><div class="card" id="upgrade-dialog" {...test('upgrade-dialog')}><h2>Choose one charm</h2><div class="upgrade-grid">{g.offers.map(id=><button id={`upgrade-${id}`} {...test(`upgrade-${id}`)} onClick={()=>{chooseUpgrade(g,id);setLife(g,'playing',rerender)}}><b>{names[id][0]}</b><br/>{names[id][1]}</button>)}</div></div></div>}{(g.life==='won'||g.life==='lost')&&<div class="overlay"><div class="card"><h2>{g.life==='won'?'DELIVERED!':'CHARM SUNDERED'}</h2><p>{g.life==='won'?`Score ${g.score}. The gate holds.`:'The keep keeps its tithe.'}</p><button id="restart-button" {...test('restart-button')} onClick={start}>Run again</button></div></div>}
 <div class="touch"><div id="joystick-zone" {...test('joystick-zone')} class="joystick" role="application" aria-label="Movement joystick" onPointerDown={e=>{pointers.current.set(e.pointerId,{kind:'move',...vector(e.currentTarget as HTMLElement,e.clientX,e.clientY)});(e.currentTarget as HTMLElement).setPointerCapture?.(e.pointerId);syncHeld()}} onPointerMove={pointerMove as any} onPointerUp={e=>{pointers.current.delete(e.pointerId);syncHeld()}} onPointerCancel={e=>{pointers.current.delete(e.pointerId);syncHeld()}} onLostPointerCapture={e=>{pointers.current.delete(e.pointerId);syncHeld()}} onTouchStart={e=>{e.preventDefault();for(const t of Array.from(e.changedTouches))touches.current.set(t.identifier,{kind:'move',...vector(e.currentTarget as HTMLElement,t.clientX,t.clientY)});syncHeld()}} onTouchMove={touchMove as any} onTouchEnd={touchEnd as any} onTouchCancel={touchEnd as any}/><div class="actions">{(['dash','toss','brace','interact'] as const).map(k=><button id={`${k}-button`} {...test(`${k}-button`)} aria-label={k==='interact'?'Use':k[0].toUpperCase()+k.slice(1)} onClick={()=>{if(k!=='brace')doAct(k)}} onPointerDown={e=>actionPointer(k,e as any)} onPointerUp={e=>{if(k==='brace'){pointers.current.delete(e.pointerId);syncHeld()}}} onPointerCancel={e=>{pointers.current.delete(e.pointerId);syncHeld()}} onTouchStart={e=>actionTouch(k,e as any)} onTouchEnd={touchEnd as any} onTouchCancel={touchEnd as any}>{k==='interact'?'USE':k.toUpperCase()}</button>)}</div></div></section><p class="tip" aria-live="polite">{g.message} · Room {g.room+1}/11 · Reduced motion has static telegraph labels.</p></main>}
