export type Life='title'|'playing'|'paused'|'choosing'|'won'|'lost';
export type EnemyKind='grunt'|'weaver'|'sentinel'|'warden';
export type Upgrade='quickstep-charm'|'ember-shard'|'iron-wrap'|'voltaic-core'|'steady-hand'|'charm-bearers-grip';
export type DashPhase='ready'|'anticipation'|'travel'|'recovery'|'cooldown';
export interface Enemy{id:number;kind:EnemyKind;x:number;y:number;hp:number;maxHp:number;cool:number;telegraph:number;mode:string;vx:number;vy:number;burn:number;guard:number}
export interface Projectile{x:number;y:number;dx:number;dy:number;owner:'player'|'enemy';damage:number;pierce:number;age:number}
export interface Afterimage{x:number;y:number;life:number}
export interface Interactable{kind:'parcel'|'door'|'chest'|'altar';x:number;y:number;inRange:boolean;locked:boolean;label:string;reason:string;prompt:string}
export interface Game{life:Life;room:number;route:'safe'|'fast'|null;parcel:boolean;hp:number;maxHp:number;x:number;y:number;facing:number;instability:number;overloads:number;dash:number;dashMax:number;dashCooldown:number;dashPhase:DashPhase;dashPhaseFrame:number;dashStartX:number;dashStartY:number;dashDirX:number;dashDirY:number;afterimages:Afterimage[];shoot:number;shootMax:number;shootCooldown:number;muzzle:number;hitSpark:number;brace:boolean;score:number;frames:number;roomFrames:number;clockFrames:number;clockMax:number;enemies:Enemy[];projectiles:Projectile[];upgrades:Upgrade[];offers:Upgrade[];chests:number;gate:boolean;key:boolean;crates:number;message:string;bossPhase:number;bossPattern:string;hazard:number;runeFrames:number;runeCharges:number;events:Record<string,number>;lossReason:string}
export const rooms=[{id:'threshold',name:'Courier Threshold',type:'start'},{id:'gallery',name:'Dust Gallery',type:'combat'},{id:'junction-a',name:'Forked Passage',type:'branch'},{id:'antechamber',name:'Vault Antechamber',type:'puzzle'},{id:'barracks',name:'Goblin Barracks',type:'combat'},{id:'junction-b',name:'Second Junction',type:'branch'},{id:'storeroom',name:'Crooked Storeroom',type:'upgrade'},{id:'cracked',name:'Cracked Hall',type:'hazard'},{id:'shrine',name:'Shrine Approach',type:'rest'},{id:'arena',name:'Iron-Tithe Arena',type:'boss'},{id:'delivery',name:'Moonseal Destination',type:'goal'}] as const;
const ev=(g:Game,k:string,n=1)=>g.events[k]=(g.events[k]||0)+n;
const enemy=(id:number,kind:EnemyKind,x:number,y:number,hp:number,cool=30):Enemy=>({id,kind,x,y,hp,maxHp:hp,cool,telegraph:0,mode:'idle',vx:0,vy:0,burn:0,guard:kind==='sentinel'?1:0});
const foes=(r:number):Enemy[]=>r===1?[enemy(1,'grunt',610,210,20,25),enemy(2,'grunt',760,410,20,55)]:r===4?[enemy(3,'grunt',580,180,20),enemy(4,'grunt',700,300,20,30),enemy(5,'grunt',580,440,20,60),enemy(6,'sentinel',790,300,60,70)]:r===7?[enemy(7,'weaver',690,175,10,35),enemy(8,'weaver',720,430,10,70)]:r===9?[enemy(9,'warden',700,300,220,80)]:[];
export function fresh():Game{return{life:'title',room:0,route:null,parcel:false,hp:80,maxHp:80,x:150,y:300,facing:0,instability:0,overloads:0,dash:1,dashMax:1,dashCooldown:0,dashPhase:'ready',dashPhaseFrame:0,dashStartX:150,dashStartY:300,dashDirX:1,dashDirY:0,afterimages:[],shoot:3,shootMax:3,shootCooldown:0,muzzle:0,hitSpark:0,brace:false,score:0,frames:0,roomFrames:0,clockFrames:60*420,clockMax:60*420,enemies:[],projectiles:[],upgrades:[],offers:[],chests:0,gate:false,key:false,crates:2,message:'Pick up the glowing parcel.',bossPhase:0,bossPattern:'',hazard:0,runeFrames:0,runeCharges:0,events:{},lossReason:''}}
export function enter(g:Game,n:number){g.room=Math.max(0,Math.min(10,n));g.x=150;g.y=300;g.roomFrames=0;g.enemies=foes(g.room);g.projectiles=[];g.hazard=0;g.runeFrames=0;g.afterimages=[];g.message=objective(g)}
const clear=(g:Game)=>!g.enemies.length||g.enemies.every(e=>e.hp<=0);
export function objective(g:Game){if(g.room===0)return g.parcel?'Reach the marked east door.':'Pick up the glowing parcel.';if(g.room===1&&!clear(g))return 'SHOOT / F — clear the marked route.';if(g.room===2)return 'Choose a marked route: safe above, fast below.';if(g.room===3&&!g.gate)return 'SHOOT the crystal lever to unlock the door.';if(g.room===6&&g.chests<(g.route==='safe'?2:1))return 'Open the courier cache.';if(g.room===9&&!clear(g))return 'Defeat the Warden. Brace through its warning rings.';if(g.room===10)return 'Carry the parcel to the Moonseal altar.';return clear(g)?'Reach the marked door.':'Clear the route to unlock the door.'}
export function getInteractable(g:Game):Interactable{let kind:Interactable['kind']='door',x=855,y=300,locked=!clear(g),label='ROUTE DOOR',reason='Clear the threats';if(g.room===0&&!g.parcel){kind='parcel';x=365;y=300;locked=false;label='GLOWING PARCEL';reason=''}else if(g.room===0){locked=false;reason=''}else if(g.room===2){x=820;y=g.y<300?150:450;locked=false;label=g.y<300?'SAFE ROUTE':'FAST ROUTE';reason=''}else if(g.room===3){locked=!g.gate;reason='Crystal lever is sealed'}else if(g.room===5){x=820;y=g.y>330?450:150;locked=false;label=g.y>330?'CACHE ROUTE':'KEEP ROUTE';reason=''}else if(g.room===6&&g.chests<(g.route==='safe'?2:1)){kind='chest';x=520;y=300;locked=false;label='COURIER CACHE';reason=''}else if(g.room===8){locked=false;reason=''}else if(g.room===10){kind='altar';x=790;y=300;locked=!g.parcel;label='MOONSEAL DESTINATION';reason='Parcel required'}const inRange=Math.hypot(g.x-x,g.y-y)<=72;return{kind,x,y,inRange,locked,label,reason,prompt:inRange?(locked?`LOCKED — ${reason}`:`USE / E — ${label}`):''}}
export function damage(g:Game,n:number){if(g.dashPhase==='travel'||g.brace)return;if(g.brace){ev(g,'blocked');return}g.hp-=n;g.instability+=g.upgrades.includes('iron-wrap')?7.2:6;ev(g,'damageTaken',n);if(g.hp<=0){g.life='lost';g.lossReason='COURIER DOWN'}}
const inRune=(g:Game)=>((g.room===6||g.room===9)&&Math.hypot(g.x-480,g.y-300)<82);
function fireEnemy(g:Game,e:Enemy,spread=0){const a=Math.atan2(g.y-e.y,g.x-e.x)+spread;g.projectiles.push({x:e.x,y:e.y,dx:Math.cos(a)*4.2,dy:Math.sin(a)*4.2,owner:'enemy',damage:12,pierce:0,age:0});ev(g,'enemyShots')}
function enemyStep(g:Game,e:Enemy){if(e.hp<=0)return;e.cool--;if(e.burn>0){e.burn--;if(e.burn%15===0)e.hp-=2};const d=Math.hypot(g.x-e.x,g.y-e.y);if(e.telegraph>0){e.telegraph--;if(!e.telegraph){if(e.kind==='weaver')fireEnemy(g,e);else if(e.kind==='warden'){if(e.mode==='volley')[-.28,0,.28].forEach(a=>fireEnemy(g,e,a));else if(e.mode==='surge'&&!inRune(g))damage(g,24);else if(d<190)damage(g,12)}else{const a=Math.atan2(g.y-e.y,g.x-e.x);e.vx=Math.cos(a)*7;e.vy=Math.sin(a)*7}e.cool=e.kind==='warden'?80:70}}else if(e.cool<=0&&d<360){e.telegraph=e.kind==='warden'?35:e.kind==='weaver'?30:e.kind==='sentinel'?40:18;e.mode=e.kind==='warden'?((g.events.bossPatterns||0)%3===2?'surge':(g.events.bossPatterns||0)%3===1?'volley':'sweep'):'windup';if(e.kind==='warden'){ev(g,'bossPatterns');g.bossPattern=e.mode}}if(e.vx||e.vy){e.x+=e.vx;e.y+=e.vy;e.vx*=.91;e.vy*=.91;if(d<34)damage(g,e.kind==='sentinel'?20:8)}if(e.kind==='warden'){const phase=e.hp/e.maxHp>.66?1:e.hp/e.maxHp>.33?2:3;if(phase!==g.bossPhase){g.bossPhase=phase;ev(g,'bossPhases')}}}
function dashStep(g:Game){if(g.dashPhase==='anticipation'){if(++g.dashPhaseFrame>=4){g.dashPhase='travel';g.dashPhaseFrame=0}}else if(g.dashPhase==='travel'){g.dashPhaseFrame++;const speed=12;g.x=Math.max(55,Math.min(905,g.x+g.dashDirX*speed));g.y=Math.max(75,Math.min(525,g.y+g.dashDirY*speed));if(g.dashPhaseFrame%2===0)g.afterimages.push({x:g.x,y:g.y,life:14});if(g.dashPhaseFrame>=8){g.dashPhase='recovery';g.dashPhaseFrame=0}}else if(g.dashPhase==='recovery'){if(++g.dashPhaseFrame>=5){g.dashPhase='cooldown';g.dashPhaseFrame=0}}else if(g.dashPhase==='cooldown'&&g.dashCooldown<=0){g.dashPhase='ready';g.dashPhaseFrame=0}g.afterimages.forEach(a=>a.life--);g.afterimages=g.afterimages.filter(a=>a.life>0)}
export function update(g:Game,keys:Set<string>){if(g.life!=='playing')return;g.frames++;g.roomFrames++;g.clockFrames--;if(g.clockFrames<=0){g.clockFrames=0;g.life='lost';g.lossReason='DELIVERY LATE';return}if(g.muzzle>0)g.muzzle--;if(g.hitSpark>0)g.hitSpark--;if(g.dashCooldown>0&&!--g.dashCooldown&&g.dash<g.dashMax)g.dash++;if(g.shootCooldown>0&&!--g.shootCooldown&&g.shoot<g.shootMax)g.shoot++;dashStep(g);let dx=(keys.has('right')?1:0)-(keys.has('left')?1:0),dy=(keys.has('down')?1:0)-(keys.has('up')?1:0);g.brace=keys.has('brace');if((dx||dy)&&g.dashPhase!=='travel'&&g.dashPhase!=='anticipation'){const l=Math.hypot(dx,dy);dx/=l;dy/=l;g.facing=Math.atan2(dy,dx);g.x=Math.max(55,Math.min(905,g.x+dx*3.4));g.y=Math.max(75,Math.min(525,g.y+dy*3.4))}if(g.brace)g.instability+=g.upgrades.includes('steady-hand')?.2:.4;else if(!inRune(g)&&g.instability<100)g.instability=Math.max(0,g.instability-.15);if(inRune(g)){g.runeFrames++;if(g.runeFrames%120===0&&g.shoot<g.shootMax){g.shoot++;g.runeCharges++;ev(g,'runeCharges')}}if(g.instability>=100){g.instability=0;g.overloads++;g.hp-=20;ev(g,'overloads');if(g.overloads>=3||g.hp<=0){g.life='lost';g.lossReason='CHARM OVERLOAD'}}if(g.room===7&&g.x>330&&g.x<650){g.hazard++;if(g.hazard===45)g.message='CRACKED FLOOR — KEEP MOVING';if(g.hazard>90&&g.hazard%45===0)damage(g,10)}else g.hazard=Math.max(0,g.hazard-2);for(const p of g.projectiles){p.age++;p.x+=p.dx;p.y+=p.dy;if(p.owner==='player')for(const e of g.enemies){if(e.hp>0&&Math.hypot(p.x-e.x,p.y-e.y)<30){e.hp-=p.damage;e.burn=g.upgrades.includes('ember-shard')?45:e.burn;g.hitSpark=8;ev(g,'playerHits');if(p.pierce--<=0)p.x=-999;break}}else if(Math.hypot(p.x-g.x,p.y-g.y)<25){damage(g,p.damage);p.x=-999}}g.projectiles=g.projectiles.filter(p=>p.x>0&&p.x<960&&p.y>0&&p.y<600);g.enemies.forEach(e=>enemyStep(g,e));g.message=objective(g)}
export function chooseUpgrade(g:Game,id:Upgrade){if(g.life!=='choosing'||!g.offers.includes(id)||g.upgrades.includes(id))return false;g.upgrades.push(id);g.chests++;if(id==='quickstep-charm'){g.dashMax=2;g.dash=2}if(id==='charm-bearers-grip'){g.shootMax=4;g.shoot=4}if(id==='iron-wrap'){g.maxHp=100;g.hp+=20}g.offers=[];g.life='playing';ev(g,'upgradesChosen');return true}
export function openChest(g:Game,slot:number){const sets:Upgrade[][]=[['quickstep-charm','iron-wrap','voltaic-core'],['ember-shard','steady-hand','charm-bearers-grip']];g.offers=sets[slot].filter(x=>!g.upgrades.includes(x));g.life='choosing';ev(g,'chestsOpened')}
export function act(g:Game,a:string){if(g.life!=='playing')return;if(a==='dash'&&g.dash>0&&g.dashPhase==='ready'){g.dash--;g.dashCooldown=50;g.dashPhase='anticipation';g.dashPhaseFrame=0;g.dashStartX=g.x;g.dashStartY=g.y;g.dashDirX=Math.cos(g.facing);g.dashDirY=Math.sin(g.facing);ev(g,'dashes')}if(a==='shoot'&&g.shoot>0){g.shoot--;g.shootCooldown=60;g.muzzle=7;g.projectiles.push({x:g.x+Math.cos(g.facing)*24,y:g.y+Math.sin(g.facing)*24,dx:Math.cos(g.facing)*10,dy:Math.sin(g.facing)*10,owner:'player',damage:8,pierce:g.upgrades.includes('ember-shard')?1:0,age:0});ev(g,'shoots');if(g.room===3){g.gate=true;ev(g,'levers')}}if(a==='interact'){const i=getInteractable(g);if(!i.inRange||i.locked){ev(g,'rejectedInteractions');return}if(i.kind==='parcel'){g.parcel=true;g.message=objective(g);ev(g,'parcelPicked');return}if(i.kind==='chest'){openChest(g,1);return}if(i.kind==='altar'){g.life='won';g.score=Math.max(100,g.clockFrames+Math.floor(g.hp*25)-g.overloads*250+g.upgrades.length*300);ev(g,'wins');return}if(g.room===0)enter(g,1);else if(g.room===1)enter(g,2);else if(g.room===2){g.route=g.y<300?'safe':'fast';enter(g,g.route==='safe'?3:4)}else if(g.room===3){if(g.chests===0)openChest(g,0);else enter(g,5)}else if(g.room===4)enter(g,5);else if(g.room===5)enter(g,g.y>330?6:7);else if(g.room===6)enter(g,5);else if(g.room===7)enter(g,8);else if(g.room===8)enter(g,9);else if(g.room===9)enter(g,10)}}
