export type Life='title'|'playing'|'paused'|'choosing'|'won'|'lost';
export type EnemyKind='grunt'|'weaver'|'sentinel'|'warden';
export type Upgrade='quickstep-charm'|'ember-shard'|'iron-wrap'|'voltaic-core'|'steady-hand'|'charm-bearers-grip';
export interface Enemy {id:number;kind:EnemyKind;x:number;y:number;hp:number;maxHp:number;cool:number;telegraph:number;mode:string;vx:number;vy:number;burn:number;guard:number}
export interface Projectile {x:number;y:number;dx:number;dy:number;owner:'player'|'enemy';damage:number;pierce:number}
export interface Game {life:Life;room:number;route:'safe'|'fast'|null;hp:number;maxHp:number;x:number;y:number;facing:number;instability:number;overloads:number;dash:number;dashMax:number;dashCooldown:number;toss:number;tossMax:number;tossCooldown:number;dashFrames:number;invulnerable:number;brace:boolean;score:number;frames:number;roomFrames:number;enemies:Enemy[];projectiles:Projectile[];upgrades:Upgrade[];offers:Upgrade[];chests:number;gate:boolean;key:boolean;crates:number;message:string;bossPhase:number;bossPattern:string;hazard:number;runeFrames:number;runeCharges:number;events:Record<string,number>}
export const rooms=[
 {id:'threshold',name:'Threshold',type:'start'}, {id:'gallery',name:'Dust Gallery',type:'combat'},
 {id:'junction-a',name:'Forked Passage',type:'branch'}, {id:'antechamber',name:'Vault Antechamber',type:'puzzle'},
 {id:'barracks',name:'Goblin Barracks',type:'combat'}, {id:'junction-b',name:'Second Junction',type:'branch'},
 {id:'storeroom',name:'Crooked Storeroom',type:'upgrade'}, {id:'cracked',name:'Cracked Hall',type:'hazard'},
 {id:'shrine',name:'Shrine Approach',type:'rest'}, {id:'arena',name:'Iron-Tithe Arena',type:'boss'},
 {id:'delivery',name:'Vault of Delivery',type:'goal'}
] as const;
const ev=(g:Game,k:string,n=1)=>g.events[k]=(g.events[k]||0)+n;
const enemy=(id:number,kind:EnemyKind,x:number,y:number,hp:number,cool=30):Enemy=>({id,kind,x,y,hp,maxHp:hp,cool,telegraph:0,mode:'idle',vx:0,vy:0,burn:0,guard:kind==='sentinel'?1:0});
const foes=(room:number):Enemy[]=>room===1?[enemy(1,'grunt',610,210,20,25),enemy(2,'grunt',760,410,20,55)]:room===4?[enemy(3,'grunt',580,180,20),enemy(4,'grunt',700,300,20,30),enemy(5,'grunt',580,440,20,60),enemy(6,'sentinel',790,300,60,70)]:room===7?[enemy(7,'weaver',690,175,10,35),enemy(8,'weaver',720,430,10,70)]:room===9?[enemy(9,'warden',700,300,220,80)]:[];
export function fresh():Game{return {life:'title',room:0,route:null,hp:80,maxHp:80,x:150,y:300,facing:0,instability:0,overloads:0,dash:1,dashMax:1,dashCooldown:0,toss:3,tossMax:3,tossCooldown:0,dashFrames:0,invulnerable:0,brace:false,score:0,frames:0,roomFrames:0,enemies:[],projectiles:[],upgrades:[],offers:[],chests:0,gate:false,key:false,crates:2,message:'The tithe-charm is waiting. Deliver it before it breaks.',bossPhase:0,bossPattern:'',hazard:0,runeFrames:0,runeCharges:0,events:{}}}
export function enter(g:Game,n:number){g.room=Math.max(0,Math.min(10,n));g.x=150;g.y=300;g.roomFrames=0;g.enemies=foes(g.room);g.projectiles=[];g.hazard=0;g.runeFrames=0;g.message=rooms[g.room].name;if(g.room===8){g.instability=Math.max(0,g.instability-20);g.message='Breathe. Instability settles before the Warden.'}if(g.room===10)g.message='The shrine gate awaits. Use the altar to deliver.'}
export function damage(g:Game,n:number){if(g.invulnerable>0)return;if(g.brace){ev(g,'blocked');return}const gain=g.upgrades.includes('iron-wrap')?7.2:6;g.hp-=n;g.instability+=gain;ev(g,'damageTaken',n);g.invulnerable=18;if(g.hp<=0)g.life='lost'}
const inRune=(g:Game)=>((g.room===6||g.room===9)&&Math.hypot(g.x-480,g.y-300)<82);
const surgeAt=(g:Game)=>g.upgrades.includes('voltaic-core')?40:60;
function fireEnemy(g:Game,e:Enemy,spread=0){const a=Math.atan2(g.y-e.y,g.x-e.x)+spread;g.projectiles.push({x:e.x,y:e.y,dx:Math.cos(a)*4.2,dy:Math.sin(a)*4.2,owner:'enemy',damage:12,pierce:0});ev(g,'enemyShots')}
function enemyStep(g:Game,e:Enemy){if(e.hp<=0)return;if(e.burn>0){e.burn--;if(e.burn%15===0)e.hp-=2}e.cool--;
 if(e.kind==='grunt'){if(e.telegraph>0){e.telegraph--;e.mode='lunge';if(!e.telegraph){const a=Math.atan2(g.y-e.y,g.x-e.x);e.vx=Math.cos(a)*7;e.vy=Math.sin(a)*7;e.cool=70}}else if(Math.hypot(g.x-e.x,g.y-e.y)<260&&e.cool<=0){e.telegraph=18;e.mode='windup';ev(g,'gruntTelegraphs')}else{e.x+=Math.sin((g.frames+e.id*19)/40)*.7;e.y+=Math.cos((g.frames+e.id*23)/50)*.55}if(e.vx||e.vy){e.x+=e.vx;e.y+=e.vy;e.vx*=.91;e.vy*=.91;if(Math.abs(e.vx)<.2){e.vx=e.vy=0;e.mode='idle'}}if(Math.hypot(g.x-e.x,g.y-e.y)<31){damage(g,8);e.cool=55}}
 if(e.kind==='weaver'){e.y+=Math.sin((g.frames+e.id*31)/60)*.25;if(e.telegraph>0){e.telegraph--;e.mode='casting';if(!e.telegraph){fireEnemy(g,e);e.cool=90;e.mode='idle'}}else if(e.cool<=0){e.telegraph=30;ev(g,'weaverTelegraphs')}}
 if(e.kind==='sentinel'){const d=Math.hypot(g.x-e.x,g.y-e.y);if(e.telegraph>0){e.telegraph--;e.mode='charge';if(!e.telegraph){const a=Math.atan2(g.y-e.y,g.x-e.x);e.vx=Math.cos(a)*8;e.vy=Math.sin(a)*8;e.cool=100;ev(g,'sentinelCharges')}}else if(e.vx||e.vy){e.x+=e.vx;e.y+=e.vy;e.vx*=.94;e.vy*=.94;if(d<38){if(g.brace){e.vx=e.vy=0;e.cool=130;e.guard=0;ev(g,'parries')}else damage(g,20)}if(Math.abs(e.vx)<.3)e.vx=e.vy=0}else if(d<330&&e.cool<=0){e.telegraph=45;e.mode='guard-charge';ev(g,'sentinelTelegraphs')}else if(d>90){e.x+=(g.x-e.x)/d*.65;e.y+=(g.y-e.y)/d*.65}}
 if(e.kind==='warden'){const frac=e.hp/e.maxHp,phase=frac>.66?1:frac>.33?2:3;if(phase!==g.bossPhase){g.bossPhase=phase;ev(g,'bossPhases');g.message=`WARDEN PHASE ${phase}: ${phase===3?'RUNE SHELTER':'READ THE TELEGRAPH'}`}if(e.telegraph>0){e.telegraph--;if(!e.telegraph){if(e.mode==='sweep'){if(Math.hypot(g.x-e.x,g.y-e.y)<190)damage(g,12);ev(g,'bossSweeps')}else if(e.mode==='volley'){[-.28,0,.28].forEach(a=>fireEnemy(g,e,a));ev(g,'bossVolleys')}else if(e.mode==='surge'){if(!inRune(g))damage(g,24);ev(g,'bossSurges')}e.cool=phase===3?70:100}}else if(e.cool<=0){const cycle=(g.events.bossPatterns||0)%3;e.mode=phase===1?(cycle?'sweep':'slam'):phase===2?(cycle===1?'volley':'sweep'):(cycle===2?'surge':cycle===1?'volley':'sweep');e.telegraph=e.mode==='surge'?55:e.mode==='volley'?35:28;g.bossPattern=e.mode;ev(g,'bossPatterns')}if(phase===3){const d=Math.hypot(g.x-e.x,g.y-e.y);if(d>110){e.x+=(g.x-e.x)/d*.85;e.y+=(g.y-e.y)/d*.85}}}
}
export function update(g:Game,keys:Set<string>){if(g.life!=='playing')return;g.frames++;g.roomFrames++;if(g.invulnerable>0)g.invulnerable--;if(g.dashCooldown>0&&!--g.dashCooldown&&g.dash<g.dashMax){g.dash++;if(g.dash<g.dashMax)g.dashCooldown=45}if(g.tossCooldown>0&&!--g.tossCooldown&&g.toss<g.tossMax){g.toss++;if(g.toss<g.tossMax)g.tossCooldown=60}
 let dx=(keys.has('right')?1:0)-(keys.has('left')?1:0),dy=(keys.has('down')?1:0)-(keys.has('up')?1:0);const raising=keys.has('brace')||inRune(g);g.brace=keys.has('brace');if(dx||dy){const l=Math.hypot(dx,dy);dx/=l;dy/=l;g.facing=Math.atan2(dy,dx);const speed=(g.instability>=surgeAt(g)?3.75:3.4)*(g.dashFrames>0?2.2:1);g.x=Math.max(55,Math.min(905,g.x+dx*speed));g.y=Math.max(75,Math.min(525,g.y+dy*speed))}if(g.dashFrames>0){g.dashFrames--;g.invulnerable=Math.max(g.invulnerable,2)}
 if(g.brace)g.instability+=g.upgrades.includes('steady-hand')?.2:.4;if(inRune(g)&&g.bossPhase<3){g.instability+=.5;g.runeFrames++;const rate=g.upgrades.includes('charm-bearers-grip')?60:120;if(g.runeFrames%rate===0&&g.toss<g.tossMax){g.toss++;g.runeCharges++;ev(g,'runeCharges')}}else if(!raising&&g.instability<60&&!g.upgrades.includes('voltaic-core'))g.instability=Math.max(0,g.instability-.15);
 if(g.instability>=90&&g.frames%30===0)damage(g,g.maxHp*.01);if(g.instability>=100){g.instability=0;g.overloads++;g.hp-=20;ev(g,'overloads');g.message=`OVERLOAD ${g.overloads}/3`;if(g.overloads>=3||g.hp<=0)g.life='lost'}
 if(g.room===7&&g.x>330&&g.x<650){g.hazard++;if(g.hazard===45){g.message='CRACKED FLOOR — MOVE!';ev(g,'hazardWarnings')}if(g.hazard>90&&g.hazard%45===0){damage(g,10);ev(g,'hazardHits')}}else g.hazard=Math.max(0,g.hazard-2);
 for(const p of g.projectiles){p.x+=p.dx;p.y+=p.dy;if(p.owner==='player'){for(const e of g.enemies){if(e.hp<=0||Math.hypot(p.x-e.x,p.y-e.y)>=30)continue;let hit=p.damage*(g.instability>=surgeAt(g)?1.25:1);if(e.kind==='sentinel'&&e.guard)hit*=.35;e.hp-=hit;if(e.telegraph&&e.kind==='weaver'){e.telegraph=0;e.cool=70;e.mode='interrupted';ev(g,'interrupts')}if(g.upgrades.includes('ember-shard'))e.burn=45;ev(g,'playerHits');if(p.pierce--<=0)p.x=-999;break}}else if(Math.hypot(p.x-g.x,p.y-g.y)<25){damage(g,p.damage);p.x=-999;ev(g,'enemyProjectileHits')}}g.projectiles=g.projectiles.filter(p=>p.x>0&&p.x<960&&p.y>0&&p.y<600);
 for(const e of g.enemies)enemyStep(g,e);if(g.enemies.length&&g.enemies.every(e=>e.hp<=0)){ev(g,'roomsCleared');g.message=g.room===9?'The Warden falls. The delivery vault is open.':'Room clear — the way forward is open.'}
}
export function chooseUpgrade(g:Game,id:Upgrade){if(g.life!=='choosing'||!g.offers.includes(id)||g.upgrades.includes(id))return false;g.upgrades.push(id);g.chests++;if(id==='quickstep-charm'){g.dashMax=2;g.dash=2}if(id==='charm-bearers-grip'){g.tossMax=4;g.toss=4}if(id==='iron-wrap'){g.maxHp=100;g.hp=Math.min(g.maxHp,g.hp+20)}g.offers=[];g.life='playing';ev(g,'upgradesChosen');return true}
export function openChest(g:Game,slot:number){const sets:Upgrade[][]=[['quickstep-charm','iron-wrap','voltaic-core'],['ember-shard','steady-hand','charm-bearers-grip']];g.offers=sets[slot].filter(x=>!g.upgrades.includes(x));g.life='choosing';ev(g,'chestsOpened')}
export function act(g:Game,a:string){if(g.life!=='playing')return;if(a==='dash'&&g.dash>0){g.dash--;g.dashFrames=12;g.invulnerable=8;if(!g.dashCooldown)g.dashCooldown=45;g.x=Math.max(55,Math.min(905,g.x+Math.cos(g.facing)*72));g.y=Math.max(75,Math.min(525,g.y+Math.sin(g.facing)*72));ev(g,'dashes')}if(a==='toss'&&g.toss>0){g.toss--;if(!g.tossCooldown)g.tossCooldown=60;g.projectiles.push({x:g.x,y:g.y,dx:Math.cos(g.facing)*9,dy:Math.sin(g.facing)*9,owner:'player',damage:6,pierce:g.upgrades.includes('ember-shard')?1:0});ev(g,'tosses');if(g.room===3){g.gate=true;g.message='The shard strikes the lever. Gate open!';ev(g,'levers')}}
 if(a==='interact'){const clear=!g.enemies.length||g.enemies.every(e=>e.hp<=0);if(g.room===0){enter(g,1);return}if(g.room===1&&clear){enter(g,2);return}if(g.room===2){g.route=g.y<300?'safe':'fast';enter(g,g.route==='safe'?3:4);return}if(g.room===3&&g.gate){if(g.chests===0)openChest(g,0);else enter(g,5);return}if(g.room===4&&clear){enter(g,5);return}if(g.room===5){if(g.y>365&&g.chests<2){enter(g,6);return}enter(g,7);return}if(g.room===6){if(g.chests<(g.route==='safe'?2:1))openChest(g,1);else enter(g,5);return}if(g.room===7&&clear){enter(g,8);return}if(g.room===8){enter(g,9);return}if(g.room===9&&clear){enter(g,10);return}if(g.room===10){g.life='won';g.score=Math.max(100,6000-g.frames+Math.floor(g.hp*25)-g.overloads*250+g.upgrades.length*300);ev(g,'wins')}}}
