const { chromium } = require('playwright');
const path = require('path');
const { pathToFileURL } = require('url');

(async () => {
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox', '--disable-gpu'] });
  const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  await page.goto(pathToFileURL(path.resolve(__dirname, '../dist-test/index.html')).href);
  await page.locator('canvas').waitFor({ state: 'visible' });
  await page.waitForFunction(() => window.gameTest);
  await page.screenshot({ path: path.resolve(__dirname, '../title.png') });
  let s = await page.evaluate(() => window.gameTest.snapshot());
  if (s.mode !== 'title') throw new Error(`expected title, got ${s.mode}`);
  await page.keyboard.press('Enter');
  await page.keyboard.down('ArrowRight');
  await page.waitForTimeout(500);
  await page.keyboard.up('ArrowRight');
  s = await page.evaluate(() => window.gameTest.snapshot());
  if (s.mode !== 'playing' || s.x <= 110) throw new Error(`movement failed: ${JSON.stringify(s)}`);
  await page.screenshot({ path: path.resolve(__dirname, '../gameplay.png') });
  await page.keyboard.press('KeyE');
  await page.waitForTimeout(100);
  s = await page.evaluate(() => window.gameTest.snapshot());
  if (s.emberCarried) throw new Error('ember placement failed');
  await page.evaluate(() => { window.gameTest.teleport(1480, 520); window.gameTest.light(0); });
  await page.waitForTimeout(100);
  s = await page.evaluate(() => window.gameTest.snapshot());
  if (s.lit !== 1) throw new Error(`hearth activation failed: ${JSON.stringify(s)}`);
  await page.evaluate(() => { window.gameTest.teleport(3460, 520); window.gameTest.light(1); });
  await page.waitForTimeout(100);
  await page.evaluate(() => { window.gameTest.teleport(5630, 170); window.gameTest.light(2); });
  await page.waitForTimeout(100);
  s = await page.evaluate(() => window.gameTest.snapshot());
  if (s.mode !== 'won') throw new Error(`ending failed: ${JSON.stringify(s)}`);
  await page.screenshot({ path: path.resolve(__dirname, '../playtest.png') });
  await browser.close();
  if (errors.length) throw new Error(errors.join('\n'));
  console.log('playtest-ok: movement, ember placement, checkpoint, and ending');
})().catch(e => { console.error(e); process.exit(1); });
