const {chromium}=require('playwright');
const fs=require('fs'),path=require('path');
const {pathToFileURL}=require('url');
const root=path.resolve(__dirname,'..'),scenarioPath=path.join(__dirname,'scenarios.json'),gallery=path.join(root,'artifacts/gallery'),reportPath=path.join(root,'artifacts/playtest-report.json');
const mapping={up:['ArrowUp','ArrowUp'],down:['ArrowDown','ArrowDown'],left:['ArrowLeft','ArrowLeft'],right:['ArrowRight','ArrowRight'],dash:['Space',' '],toss:['KeyF','f'],brace:['KeyJ','j'],interact:['KeyE','e'],pause:['Escape','Escape'],mute:['KeyM','m']};
const kinds=new Set(['boot','core','win','loss','input','pause','regression']);
function fail(s){throw Error(s)}
function targetOk(t){if(/^@[01](?:\.\d+)?,[01](?:\.\d+)?$/.test(t)){const [x,y]=t.slice(1).split(',').map(Number);return x>=0&&x<=1&&y>=0&&y<=1}return !!t&&!/^@/.test(t)&&!/[{};]/.test(t)}
function validate(doc){if(!doc||doc.schemaVersion!==1||!Array.isArray(doc.scenarios))fail('schemaVersion/scenarios invalid');const names=new Set(),shots=new Set();let boots=0,cores=0;for(const [i,s] of doc.scenarios.entries()){if(!s||typeof s.name!=='string'||names.has(s.name))fail(`scenario ${i} duplicate/invalid name`);names.add(s.name);if(typeof s.screenshot!=='string'||!s.screenshot.endsWith('.png')||shots.has(s.screenshot))fail(`scenario ${s.name} duplicate/invalid screenshot`);shots.add(s.screenshot);if(!kinds.has(s.kind))fail(`scenario ${s.name} invalid kind`);if(s.kind==='boot')boots++;if(s.kind==='core')cores++;if(!['fresh','reload'].includes(s.start))fail(`scenario ${s.name} invalid start`);if(!Array.isArray(s.setup)||!Array.isArray(s.actions)||!s.expect||typeof s.expect.check!=='string'||!Array.isArray(s.expect.visible))fail(`scenario ${s.name} shape invalid`);if((s.kind==='boot'||s.kind==='core')&&[...s.setup,...s.actions].some(x=>x.startsWith('call:')))fail(`${s.kind} ${s.name} must be hook-free`);const ids={pointer:new Set(),touch:new Set()};for(const token of [...s.setup,...s.actions])validateToken(token,ids,s.name);if(ids.pointer.size||ids.touch.size)fail(`${s.name} has unmatched active IDs`)}if(boots!==1||cores<1)fail(`need exactly one boot and at least one core`);return doc}
function validateToken(a,ids,name){let m;if((m=a.match(/^hold:([^:]+):(\d+)$/))){if(!mapping[m[1]]||+m[2]<1)fail(`${name}: bad hold`);return}if((m=a.match(/^press:([^:]+)$/))){if(!mapping[m[1]])fail(`${name}: bad press`);return}if((m=a.match(/^release:([^:]+)$/))){if(!mapping[m[1]])fail(`${name}: bad release`);return}if((m=a.match(/^wait:(\d+)$/))){if(+m[1]<1)fail(`${name}: bad wait`);return}if((m=a.match(/^tap:(.+)$/))){if(!targetOk(m[1]))fail(`${name}: bad tap target`);return}if(/^call:[A-Za-z][\w]*\((?:.*)\)$/.test(a))return;
 if((m=a.match(/^pointer:(down|move|up|cancel):(\d+):(.+)$/))){const op=m[1],id=+m[2];if(!targetOk(m[3]))fail(`${name}: bad pointer target`);if(op==='down'){if(ids.pointer.has(id))fail(`${name}: duplicate pointer ${id}`);ids.pointer.add(id)}else if(!ids.pointer.has(id))fail(`${name}: unmatched pointer ${id}`);else if(op==='up'||op==='cancel')ids.pointer.delete(id);return}
 if((m=a.match(/^touch:(start|move|end|cancel):(\d+):(.+)$/))){const op=m[1],id=+m[2];if(!targetOk(m[3]))fail(`${name}: bad touch target`);if(op==='start'){if(ids.touch.has(id))fail(`${name}: duplicate touch ${id}`);ids.touch.add(id)}else if(!ids.touch.has(id))fail(`${name}: unmatched touch ${id}`);else if(op==='end'||op==='cancel')ids.touch.delete(id);return}fail(`${name}: unknown token ${a}`)}
const init=()=>{let now=0,seq=0,id=0,q=[];Math.random=(()=>{let s=123456789;return()=>((s=Math.imul(1664525,s)+1013904223>>>0)/4294967296)})();Date.now=()=>1700000000000+now;Object.defineProperty(performance,'now',{value:()=>now,configurable:true});const add=(cb,d,interval,type)=>{const n=++id;q.push({id:n,cb,due:now+Math.max(0,Number(d)||0),interval,seq:++seq,type});return n};requestAnimationFrame=cb=>add(cb,1000/60,0,'raf');const cancel=n=>{q=q.filter(x=>x.id!==n)};cancelAnimationFrame=clearTimeout=clearInterval=cancel;setTimeout=(cb,d=0,...a)=>add(()=>cb(...a),d,0,'timer');setInterval=(cb,d=0,...a)=>add(()=>cb(...a),d,Math.max(1,Number(d)||1),'timer');window.__step=n=>{for(let f=0;f<n;f++){now+=1000/60;let guard=0;for(;;){const due=q.filter(x=>x.type==='timer'&&x.due<=now).sort((a,b)=>a.due-b.due||a.seq-b.seq);if(!due.length)break;for(const x of due){if(!q.includes(x))continue;q=q.filter(y=>y!==x);x.cb();if(x.interval&&!q.some(y=>y.id===x.id)){x.due+=x.interval;x.seq=++seq;q.push(x)}if(++guard>10000)throw Error('timer runaway')}}const rafs=q.filter(x=>x.type==='raf'&&x.due<=now).sort((a,b)=>a.seq-b.seq);q=q.filter(x=>!rafs.includes(x));for(const x of rafs)x.cb(now)}}};
function parseCall(s){const m=s.match(/^call:([A-Za-z][\w]*)\((.*)\)$/);if(!m)fail(`bad call ${s}`);let args=[];if(m[2]){try{args=JSON.parse(`[${m[2]}]`)}catch{fail(`bad call args ${s}`)}}return [m[1],args]}
async function step(page,n=1){await page.evaluate(n=>window.__step(n),n)}
async function key(page,name,frames=1){const m=mapping[name];await page.dispatchEvent('body','keydown',{code:m[0],key:m[1],bubbles:true});await step(page,frames);await page.dispatchEvent('body','keyup',{code:m[0],key:m[1],bubbles:true})}
async function point(page,target){if(target.startsWith('@')){const [nx,ny]=target.slice(1).split(',').map(Number),b=await page.locator('.stage').boundingBox();if(!b)fail(`stage not visible`);const x=b.x+b.width*nx,y=b.y+b.height*ny,sel=nx<.42&&ny>.62?'#joystick-zone':await page.evaluate(({x,y})=>{const e=document.elementFromPoint(x,y);if(!e)return null;if(!e.id)e.id=`harness-hit-${Math.random().toString(16).slice(2)}`;return '#'+CSS.escape(e.id)},{x,y});if(!sel)fail(`no hit target ${target}`);return {sel,x,y}}const l=page.locator(target);await l.waitFor({state:'visible'});const b=await l.boundingBox();if(!b)fail(`target has no box ${target}`);return {sel:target,x:b.x+b.width/2,y:b.y+b.height/2}}
async function dispatchTouch(page,op,id,p,state){await page.evaluate(({op,id,x,y,selector,active})=>{const el=document.querySelector(selector);if(!el)throw Error(`missing touch target ${selector}`);const make=t=>new Touch({identifier:t.id,target:document.querySelector(t.selector)||el,clientX:t.x,clientY:t.y,pageX:t.x,pageY:t.y,screenX:t.x,screenY:t.y});const changed=make({id,x,y,selector});el.dispatchEvent(new TouchEvent(`touch${op}`,{touches:active.map(make),targetTouches:active.filter(t=>(document.querySelector(t.selector)||el)===el).map(make),changedTouches:[changed],bubbles:true,cancelable:true,composed:true}))},{op,id,x:p.x,y:p.y,selector:p.sel,active:[...state.values()]})}
async function action(page,a,state){let m;if((m=a.match(/^hold:([^:]+):(\d+)$/)))return key(page,m[1],+m[2]);if((m=a.match(/^press:([^:]+)$/)))return key(page,m[1]);if((m=a.match(/^release:([^:]+)$/))){const k=mapping[m[1]];return page.dispatchEvent('body','keyup',{code:k[0],key:k[1],bubbles:true})}if((m=a.match(/^wait:(\d+)$/)))return step(page,+m[1]);if((m=a.match(/^tap:(.+)$/))){const p=await point(page,m[1]);await page.dispatchEvent(p.sel,'pointerdown',{pointerId:1,pointerType:'mouse',clientX:p.x,clientY:p.y,buttons:1,bubbles:true});await step(page);await page.dispatchEvent(p.sel,'pointerup',{pointerId:1,pointerType:'mouse',clientX:p.x,clientY:p.y,buttons:0,bubbles:true});await page.dispatchEvent(p.sel,'click',{clientX:p.x,clientY:p.y,bubbles:true});return}if(a.startsWith('call:')){const [n,args]=parseCall(a);return page.evaluate(({n,args})=>{if(typeof window.__game?.[n]!=='function')throw Error(`unknown hook ${n}`);window.__game[n](...args)},{n,args})}
 if((m=a.match(/^pointer:(down|move|up|cancel):(\d+):(.+)$/))){const op=m[1],id=+m[2],p=await point(page,m[3]);if(op==='down')state.pointers.set(id,p);const target=state.pointers.get(id)||p;await page.locator(target.sel).evaluate(el=>{el.setPointerCapture=()=>{};el.releasePointerCapture=()=>{}});await page.dispatchEvent(target.sel,`pointer${op}`,{pointerId:id,pointerType:'touch',isPrimary:id===Math.min(...[...state.pointers.keys()]),clientX:p.x,clientY:p.y,buttons:op==='up'||op==='cancel'?0:1,bubbles:true,cancelable:true});if(op==='up'||op==='cancel')state.pointers.delete(id);return}
 if((m=a.match(/^touch:(start|move|end|cancel):(\d+):(.+)$/))){const op=m[1],id=+m[2],p=await point(page,m[3]);if(op==='start'||op==='move')state.touches.set(id,{id,x:p.x,y:p.y,selector:p.sel});else state.touches.delete(id);await dispatchTouch(page,op,id,p,state.touches);return}fail(`unhandled ${a}`)}
async function clearAndNavigate(page,start,url){await page.goto(url);await page.evaluate(()=>{localStorage.clear();sessionStorage.clear();document.cookie.split(';').forEach(c=>document.cookie=c.replace(/^ +/,'').replace(/=.*/,'=;expires='+new Date(0).toUTCString()+';path=/'))});if(start==='reload')await page.reload();}
async function ready(page){for(let i=0;i<180;i++){if(await page.locator('#game-ready').isVisible().catch(()=>false)&&await page.locator('canvas#game-canvas').isVisible().catch(()=>false))return;await step(page)}fail('readiness timeout')}
(async()=>{const records=[];let browser,error=null;fs.mkdirSync(gallery,{recursive:true});try{const doc=validate(JSON.parse(fs.readFileSync(scenarioPath,'utf8')));browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-setuid-sandbox','--disable-dev-shm-usage','--disable-gpu','--allow-file-access-from-files']});for(const s of doc.scenarios){const ctx=await browser.newContext({viewport:{width:960,height:760}}),page=await ctx.newPage(),errs=[];page.on('console',m=>{if(m.type()==='error')errs.push(m.text())});page.on('pageerror',e=>errs.push(e.message));const rec={scenario:s.name,pass:false,state:null,error:null,consoleErrors:errs,screenshot:s.screenshot};try{await page.addInitScript(init);await clearAndNavigate(page,s.start,pathToFileURL(path.join(root,'dist-test','index.html')).href);await ready(page);const state={pointers:new Map(),touches:new Map()};for(const a of s.setup)await action(page,a,state);for(const a of s.actions)await action(page,a,state);rec.state=await page.evaluate(()=>document.documentElement.dataset.gameState);if(rec.state!==s.expect.state)fail(`state ${rec.state} != ${s.expect.state}`);for(const v of s.expect.visible)if(!await page.locator(v).isVisible())fail(`not visible: ${v}`);const ok=await page.evaluate(expr=>{const g=window.__game,state=document.documentElement.dataset.gameState;return Function('g','state',`"use strict"; return (${expr})`)(g,state)},s.expect.check);if(ok!==true){const snapshot=await page.evaluate(()=>window.__game.getState());fail(`check false: ${s.expect.check}\nstate=${JSON.stringify(snapshot)}`)}if(errs.length)fail(errs.join('; '));rec.pass=true}catch(e){rec.error=String(e.stack||e)}try{await page.screenshot({path:path.join(gallery,s.screenshot)})}catch(e){rec.pass=false;rec.error=(rec.error?rec.error+'\n':'')+String(e)}records.push(rec);await ctx.close()}}catch(e){error=String(e.stack||e)}finally{if(browser)await browser.close();const out={schemaVersion:1,pass:!error&&records.length>0&&records.every(r=>r.pass),scenarios:records,error};fs.mkdirSync(path.dirname(reportPath),{recursive:true});fs.writeFileSync(reportPath+'.tmp',JSON.stringify(out,null,2));fs.renameSync(reportPath+'.tmp',reportPath);if(out.pass)console.log(`playtest-ok ${records.length}`);else{console.error(error||records.filter(r=>!r.pass).map(r=>`${r.scenario}: ${r.error}`).join('\n'));process.exitCode=1}}})();
